add updated linting configurations and workflow

diff --git a/.github/workflows/linting-pipeline.yaml b/.github/workflows/linting-pipeline.yaml
--- a/.github/workflows/linting-pipeline.yaml
+++ b/.github/workflows/linting-pipeline.yaml
@@ -1,4 +1,5 @@
 name: linting-pipeline
+
 on:
   push:
     branches: 
@@ -14,17 +15,20 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v4
 
-    - name: Install HTMLHint
-      run: npm install --save-dev htmlhint
-
-    - name: Install Stylelint
-      run: npm install --save-dev stylelint
+    - name: Install Dependencies
+      run: |
+        npm install --save-dev htmlhint stylelint
 
     - name: Lint HTML files
       run: npx htmlhint "**/*.html"
 
     - name: Lint CSS Files
-      run: npx stylelint "**/*.css"
-    
+      run: |
+        if ls **/*.css 1> /dev/null 2>&1; then
+          npx stylelint "**/*.css" || echo "No CSS files to lint or linting failed"
+        else
+          echo "No CSS files found, skipping linting"
+        fi
+
     - name: Lint contents of Package.json
       run: cat package.json
